import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
// import Navbar from "@/components/Navbar";
import { Anton, Poppins } from "next/font/google";

const anton = Anton({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-anton',
  display: 'swap',
});

const poppins = Poppins({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
  display: 'swap',
});

// const bristol = Bristol({
//   weight: '400',
//   subsets: ['latin'],
//   variable: '--font-bristol',
//   display: 'swap',
// })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Maïlys",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${anton.variable} ${poppins.variable}`}
      >
        {/* < Navbar visible={true} /> */}
        <main>
        {children}
        </main>
        < Footer />
      </body>
    </html>
  );
}
